services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      - wp_network

  wordpress:
    build:
      context: ./docker 
      dockerfile: Dockerfile--wordpress 
    depends_on:
      - db
      - redis
    ports:
      - "${WORDPRESS_HOST_PORT}:80" 
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./docker/custom-entrypoint.sh:/usr/local/bin/custom-entrypoint.sh
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      CUSTOM_THEME_NAME: ${CUSTOM_THEME_NAME}
      WORDPRESS_ENV: ${WORDPRESS_ENV:-development}
      WORDPRESS_REDIS_HOST: redis
      WORDPRESS_REDIS_PORT: ${WORDPRESS_REDIS_PORT:-6379}
      MSMTP_HOST: ${MSMTP_HOST:-smtp.example.com}
      MSMTP_PORT: ${MSMTP_PORT:-587}
      MSMTP_FROM: ${MSMTP_FROM:-wordpress@example.com}
      MSMTP_USER: ${MSMTP_USER:-}
      MSMTP_PASSWORD: ${MSMTP_PASSWORD:-}
      MSMTP_AUTH: ${MSMTP_AUTH:-on}
      MSMTP_TLS: ${MSMTP_TLS:-off}
      MSMTP_TLS_STARTTLS: ${MSMTP_TLS_STARTTLS:-on}
      MSMTP_LOGFILE: ${MSMTP_LOGFILE:-/tmp/msmtp.log}
    entrypoint: ["/usr/local/bin/custom-entrypoint.sh"]
    command: ["apache2-foreground"]
    networks:
      - wp_network

  redis:
    image: redis:alpine
    restart: always
    networks:
      - wp_network

volumes:
  db_data:

networks:
  wp_network:
    driver: bridge
