# Utiliser l'image WordPress officielle comme base
FROM wordpress:php8.3-apache

USER root

RUN echo "DEBUG Dockerfile: Checking for mysqladmin after USER root and before any custom installations" && \
    (which mysqladmin && echo "DEBUG Dockerfile: mysqladmin found at $(which mysqladmin)" || echo "DEBUG Dockerfile: mysqladmin NOT found at this stage") && \
    echo "DEBUG Dockerfile: PATH is $PATH"

ENV NVM_DIR=/usr/local/nvm
ENV NODE_VERSION=22.10.0


RUN apt-get update && apt-get install -y --no-install-recommends \   
    libz-dev \
    libssl-dev \
    msmtp \
    ca-certificates \
    curl \
    git \
    unzip \
    gzip \
    libtool \
  && pecl install redis \
  && docker-php-ext-enable redis \
  && curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
  && chmod +x wp-cli.phar \
  && mv wp-cli.phar /usr/local/bin/wp \
  && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
  && mkdir -p $NVM_DIR \
  && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash \
  && . $NVM_DIR/nvm.sh \
  && nvm install $NODE_VERSION \
  && nvm use $NODE_VERSION \
  && nvm alias default $NODE_VERSION \
  && mkdir -p /usr/local/etc/php/conf.d \
  && printf "[PHP]\\nsendmail_path = /usr/bin/msmtp -t -i\\nupload_max_filesize = 500M\\npost_max_size = 500M\\nmemory_limit = 256M\\n" > /usr/local/etc/php/conf.d/zz-custom-php-settings.ini \
  && echo "DEBUG Dockerfile: Checking for mysqladmin after custom installations and before cleanup" && \
     (which mysqladmin && echo "DEBUG Dockerfile: mysqladmin found at $(which mysqladmin)" || echo "DEBUG Dockerfile: mysqladmin NOT found before cleanup") && \
     echo "DEBUG Dockerfile: PATH is $PATH" && \
  apt-get autoremove -y --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && echo "DEBUG Dockerfile: Checking for mysqladmin after cleanup" && \
     (which mysqladmin && echo "DEBUG Dockerfile: mysqladmin found at $(which mysqladmin)" || echo "DEBUG Dockerfile: mysqladmin NOT found after cleanup") && \
     echo "DEBUG Dockerfile: PATH is $PATH"

ENV PATH=$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

COPY custom-entrypoint.sh /usr/local/bin/custom-entrypoint.sh
RUN chmod +x /usr/local/bin/custom-entrypoint.sh
